{-# LANGUAGE OverloadedStrings #-}

-- | GENERATED FILE -- do not edit by hand. Regenerated by
-- @scripts\/emit-content-bundles.py --manifest-hs@, which
-- @scripts\/build-site.sh@ runs BEFORE the wasm build (step 3a);
-- @scripts\/check-site.sh@ fails if a fresh regeneration is not
-- byte-identical to this file.
--
-- THE BUILD-TIME EXPECTATION the running app checks every fetched
-- bundle against -- BOTH kinds (M6 gate round 1, finding M6-R1-1; M7
-- W1, briefs\/M7-plan.md ruling 1). The expectation deliberately lives
-- HERE -- compiled into app.wasm -- and NOT in the bundle: a bundle
-- that carries its own manifest and fingerprint proves only that it is
-- internally consistent, so a complete OLDER build, or any
-- self-consistent forgery served at the right URL, would satisfy it.
-- Checking the fetched bytes against a constant baked into a DIFFERENT
-- artifact means acceptance requires agreement between two separately
-- served files, which only the build that produced both can supply.
--
-- ONE module, not two: the exercise corpus and the manual text ship in
-- the same bundle grammar under the same acceptance rules, and their
-- expectations are regenerated together by one emitter run, so keeping
-- them in one generated file is what makes \"the manifest describes THIS
-- build\" checkable in a single byte-comparison (check-site's M6-g).
--
-- It carries names, counts and hashes ONLY -- never corpus or manual
-- text -- so re-embedding it costs the wasm a fraction of a percent of
-- what the retired \"Exercises.Embed\" corpus and the retired
-- TH-embedded translations cost (see each milestone's report for the
-- measured deltas).
module Bundle.Manifest
  ( manifestDecks
  , manifestDeckCount
  , manifestExercises
  , manifestPrompts
  , manifestFingerprint
    -- * M7 W1: the manual half
  , manifestManualDocs
  , manifestManualDocCount
  , manifestManualFingerprint
  ) where

import           Data.Text (Text)
import           Data.Word (Word32)

-- | Every deck file name INDEX names, in INDEX order -- the exact
-- @!SXC1-DECK@ sequence a healthy bundle must carry.
manifestDecks :: [FilePath]
manifestDecks =
  [ "000-ch0-01.ex.md"
  , "002-ch0-02.ex.md"
  , "004-ch0-03.ex.md"
  , "006-ch0-04.ex.md"
  , "008-ch0-05.ex.md"
  , "010-ch0-06.ex.md"
  , "012-ch0-07.ex.md"
  , "014-ch0-08.ex.md"
  , "016-prep-01.ex.md"
  , "018-prep-02.ex.md"
  , "020-prep-03.ex.md"
  , "022-prep-04.ex.md"
  , "024-pad-01.ex.md"
  , "026-pad-02.ex.md"
  , "028-pad-03.ex.md"
  , "030-pad-04.ex.md"
  , "032-pad-05.ex.md"
  , "034-pad-06.ex.md"
  , "036-pad-07.ex.md"
  , "038-pad-08.ex.md"
  , "040-pad-09.ex.md"
  , "042-smp-01.ex.md"
  , "044-smp-02.ex.md"
  , "046-smp-03.ex.md"
  , "048-smp-04.ex.md"
  , "050-smp-05.ex.md"
  , "052-smp-06.ex.md"
  , "054-smp-07.ex.md"
  , "056-seq-01.ex.md"
  , "058-seq-02.ex.md"
  , "060-seq-03.ex.md"
  , "062-seq-04.ex.md"
  , "064-seq-05.ex.md"
  , "066-seq-06.ex.md"
  , "068-seq-07.ex.md"
  , "070-seq-08.ex.md"
  , "072-seq-09.ex.md"
  , "074-lvl-01.ex.md"
  , "076-lvl-02.ex.md"
  , "078-lvl-03.ex.md"
  , "080-lvl-04.ex.md"
  , "082-lvl-05.ex.md"
  , "084-lvl-06.ex.md"
  , "086-lvl-07.ex.md"
  , "088-lvl-08.ex.md"
  , "090-lvl-09.ex.md"
  , "092-lvl-10.ex.md"
  , "094-lvl-11.ex.md"
  , "096-lvl-12.ex.md"
  , "098-lvl-13.ex.md"
  , "100-lvl-14.ex.md"
  , "102-lvl-15.ex.md"
  ]

manifestDeckCount :: Int
manifestDeckCount = 52

-- | Aggregate corpus counts, derived at build time from the SAME
-- emission the bundles are written from and identical for both
-- languages (the emitter refuses to emit when they disagree).
manifestExercises :: Int
manifestExercises = 435

manifestPrompts :: Int
manifestPrompts = 550

-- | FNV-1a\/32 over the WHOLE emitted exercise bundle's UTF-8 bytes --
-- the catch-all identity check
-- ("Exercises.Corpus".'Exercises.Corpus.fnv1a32' recomputes it over the
-- fetched text). 'Nothing' for a language this build did not emit.
manifestFingerprint :: Text -> Maybe Word32
manifestFingerprint "en" = Just 918201363
manifestFingerprint "ja" = Just 205948798
manifestFingerprint _    = Nothing

-- | Every manual document slug, in the reader's fixed presentation
-- order, paired with its page count (the number of
-- @\<!-- page N --\>@ markers, which are exactly 1..N) -- the precise
-- @!SXC1-DOC@ sequence a healthy manual bundle must carry. The per-doc
-- LANGUAGE each @!SXC1-DOC@ line also names is deliberately NOT pinned
-- here: it changes as wave 2 lands one document at a time, and the
-- whole-bundle fingerprint below already pins every byte of those
-- lines.
manifestManualDocs :: [(Text, Int)]
manifestManualDocs =
  [ ("guide-book", 71)
  , ("startup-guide", 15)
  , ("midi", 6)
  , ("oss", 16)
  ]

manifestManualDocCount :: Int
manifestManualDocCount = 4

-- | FNV-1a\/32 over the WHOLE emitted manual bundle's UTF-8 bytes --
-- the manual half's catch-all identity check, computed and consumed
-- exactly like 'manifestFingerprint'.
manifestManualFingerprint :: Text -> Maybe Word32
manifestManualFingerprint "en" = Just 1189317258
manifestManualFingerprint "ja" = Just 253264256
manifestManualFingerprint _    = Nothing
